version: 2.1

workflows:
  build_and_release:
    jobs:
      - build
      - build-doc:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - /^master$/
                - /^main$/
      - release-doc:
          requires:
            - build-doc
          filters:
            branches:
              only:
                - /^master$/
                - /^main$/

jobs:
  build: # yarn install
    docker:
      - image: cimg/node:15.5.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - /home/circleci/.cache/yarn/
          key: yarn-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  release: # release npm package
    docker:
      - image: cimg/node:15.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: publish package
          command: npx semantic-release
  build-doc: # build storybook
    docker:
      - image: cimg/node:15.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build storybook
          command: yarn build-doc
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static
  release-doc: # publish storybook to gh-pages
    docker:
      - image: cimg/node:15.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: publish to gh-pages
          command: |
            git config --global user.email "confluxbot@users.noreply.github.com"
            git config --global user.name "ConfluxBot"
            cd storybook-static
            cp -r ../.git ./
            git add .
            git commit -m 'feat: release to gh-pages [ci skip]'
            git push --force "https://ConfluxBot:$GH_TOKEN@github.com/Conflux-Chain/react-hooks" HEAD:gh-pages
